on:
  workflow_dispatch:
  
name: Deploy Bicep Demo

permissions:
      id-token: write
      contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUB_ID }}

      # Deploy Bicep file
    - name: Deploy the bicep file
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUB_ID }}
        resourceGroupName: RG_PolicyTest
        template: ./Part06IaC/storageaccount.bicep
        parameters: ./Part06IaC/storageaccount-dev.bad.parameters.json
