on:
  workflow_dispatch:
  
name: ReadAzureKeyVault

jobs:

  login-and-read-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure key vault - Get Secret
      uses: Azure/get-keyvault-secrets@v1
      with:
        # Name of the azure key vault
        keyvault: ${{ vars.KEYVAULTNAME}}
        # Name of the secret to be fetched
        # secrets: ${{ vars.SECRET_NAME }}
        secrets: Secret1
      id: getKeyVaultSecrets
      
    - name: Dumb thing to do with a secret
      env:
        SECRET: ${{ steps.getKeyVaultSecrets.outputs.Secret1 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Can I see $SECRET"
        if [ $SECRET = "Password" ]; then echo "That is a match"; fi
